# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swifty_Proteins' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod "PCLBlurEffectAlert"
  # Pods for Swifty_Proteins

end
